USE [master]
GO

/****** Object:  Database [CleanArchitecture]  ******/
CREATE DATABASE [CleanArchitecture]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'CleanArchitecture', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\CleanArchitecture.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'CleanArchitecture_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\CleanArchitecture_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [CleanArchitecture].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [CleanArchitecture] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [CleanArchitecture] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [CleanArchitecture] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [CleanArchitecture] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [CleanArchitecture] SET ARITHABORT OFF 
GO

ALTER DATABASE [CleanArchitecture] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [CleanArchitecture] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [CleanArchitecture] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [CleanArchitecture] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [CleanArchitecture] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [CleanArchitecture] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [CleanArchitecture] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [CleanArchitecture] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [CleanArchitecture] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [CleanArchitecture] SET  DISABLE_BROKER 
GO

ALTER DATABASE [CleanArchitecture] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [CleanArchitecture] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [CleanArchitecture] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [CleanArchitecture] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [CleanArchitecture] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [CleanArchitecture] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [CleanArchitecture] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [CleanArchitecture] SET RECOVERY FULL 
GO

ALTER DATABASE [CleanArchitecture] SET  MULTI_USER 
GO

ALTER DATABASE [CleanArchitecture] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [CleanArchitecture] SET DB_CHAINING OFF 
GO

ALTER DATABASE [CleanArchitecture] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [CleanArchitecture] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [CleanArchitecture] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [CleanArchitecture] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [CleanArchitecture] SET QUERY_STORE = OFF
GO

ALTER DATABASE [CleanArchitecture] SET  READ_WRITE 
GO


USE [CleanArchitecture]
GO

/****** Object:  Table [dbo].[Customers]  ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Customers](
	[CustomerId] [int] IDENTITY(1,1) NOT NULL,
	[Guid] [uniqueidentifier] NOT NULL,
	[FirstName] [varchar](50) NOT NULL,
	[LastName] [varchar](50) NOT NULL,
	[EmailAddress] [varchar](50) NOT NULL
) ON [PRIMARY]
GO
