name: clean-architecture

services:
  webapi:
    image: ${DOCKER_REGISTRY-}webapi
    build:
      context: .
      dockerfile: Presentation.WebApi/Dockerfile
    depends_on:
      - postgres-database
      - sqlserver-database

  postgres-database:
    image: postgres:latest
    container_name: postgres_database
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - ./dataset:/docker-entrypoint-initdb.d

  sqlserver-database:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    container_name: sqlserver_database
    restart: always
    ports:
      - 1433:1433
    env_file:
      - .env

  # pgadmin:
  #   image: dpage/pgadmin4:latest
  #   container_name: pgadmin4
  #   restart: always
  #   ports:
  #     - 5050:80
  #   env_file:
  #     - .env

